/**
 * Bold checkout — UI integration entry point.
 *
 * SECURITY: secretKey MUST NEVER reach the customer's browser.
 * The integrity hash (sha256(orderId + amount + currency + secretKey)) has to
 * be generated by a backend (Firebase Cloud Function recommended).
 *
 * Wiring plan:
 *   1. Deploy a Cloud Function `getBoldIntegrity({ orderId, amount, currency })`
 *      that reads secretKey from /settings/bold (server-side) and returns the hash.
 *   2. Replace the TODO below with httpsCallable to that function.
 *   3. Inject the bold-button script with the signed integrity hash, OR
 *      redirect to Bold's hosted checkout with the signature in the URL.
 */
export async function startBoldCheckout({ booking, publicKey }) {
  if (!publicKey) {
    throw new Error('Falta la llave pública de Bold en /settings/bold')
  }
  const reference = `parfly-${Date.now()}-${booking.id || 'new'}`
  const amount = booking.total
  const currency = 'COP'

  // TODO(integration): replace with httpsCallable('getBoldIntegrity')
  // const getIntegrity = httpsCallable(functions, 'getBoldIntegrity')
  // const { data: { integrity } } = await getIntegrity({ reference, amount, currency })
  // window.location.href = `https://checkout.bold.co/payment/${integrity}?reference=${reference}&amount=${amount}&apiKey=${publicKey}`

  console.warn(
    '[Bold] Integración en construcción. Falta Cloud Function que firme la transacción.',
    { reference, amount, currency, publicKey },
  )
  alert(
    'La pasarela Bold está activa pero la firma server-side aún no está desplegada.\n\nPor ahora, usa "Pagar por WhatsApp" para coordinar el pago manualmente.\n\n(Detalles registrados en consola)',
  )
  return { status: 'pending_backend', reference }
}

export function buildWhatsAppPaymentMessage(booking, whatsappNumber) {
  const lines = [
    'Hola Fly Parapente Tour, quiero confirmar mi reserva:',
    '',
    `🪂 Servicio: ${booking.serviceName}`,
    `📍 Sede: ${booking.sede}`,
    `📅 Fecha: ${booking.date} · ${booking.time}`,
    `👤 Nombre: ${booking.clientName}`,
    `📧 Email: ${booking.clientEmail}`,
    `📱 Teléfono: ${booking.clientPhone}`,
  ]
  if (booking.additionals?.length) {
    lines.push('', 'Adicionales:')
    booking.additionals.forEach((a) => lines.push(`  • ${a.name}`))
  }
  lines.push('', `💵 Total: $${(booking.total || 0).toLocaleString('es-CO')} COP`)
  if (booking.id) lines.push(`📝 Ref: ${booking.id}`)
  const phone = (whatsappNumber || '').replace(/\D/g, '')
  return `https://wa.me/${phone}?text=${encodeURIComponent(lines.join('\n'))}`
}
